import Head from 'next/head'
import { useSession, signIn, signOut, getSession } from 'next-auth/react'
import Creator from '../components/creator'

export default function Home() {
  const { data: session, status } = useSession()
  if (status === 'loading') {
    return <div>Loading...</div>
  }

  return (
    <section>
      <div className='container'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        {!session && (
          <>
            <h3>{session}</h3>
            <button onClick={() => signIn()}>Sign in </button>
          </>
        )}

        {session && (
          <>
            <Creator />
            <button onClick={() => signOut()}>Sign out pls</button>
          </>
        )}
      </div>
    </section>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {
      session: await getSession(context),
    },
  }
}
